### ISSUE TITLE
Feature request: download function for the payloads

### ISSUE THREAD

**Issue by ingspi** [whint/messagestore-viewer-cf#1]
I just installed the app and it works with one exception. Displaying the payload in the browser window does not work for large messages. I tried to display a payload of 14 MByte after which the browser / page did not respond anymore.
Could this be avoided with a download function/button? Furthermore, I think that would be a good feature in principle.

**Comment by dmailaender** [comment]
Hi Ingspi,

apologies for the late reply and many thanks for your feedback!

We will include the feature in our next release to be published within the next two weeks.

Best regards
David

**Comment by jmailaender** [comment]
Added in [version 1.0.2](https://github.com/whint/messagestore-viewer-cf/releases/tag/v1.0.2)
