### ISSUE TITLE
deploy command not working

### ISSUE THREAD

**Issue by hemantmathuriya** [whint/messagestore-viewer-cf#2]
Hi,

I am not able to execute deploy command. Sorry, I am new to this but how to get mtar file. If I download the code, it is a zip file and also if I execute the same command(cf deploy MessageStoreViewer_1.0.0.mtar), I get this error saying "No org and space targeted".

Could you let me know, what do I need to do to rectify this?

Thanks,
Hemant

**Comment by jmailaender** [comment]
Hi Hemant,

no problem, that means you haven't selected an organisation / space when logging in to CF.

Just do a `cf o` to list all organisations, choose one with `cf target -o <org>` then `cf s` to list all spaces and `cf target -s <space>` to set it.

Let me know if that solves your issue!

David

**Comment by hemantmathuriya** [comment]
Hi David,

Thanks for quick response. We have now selected organization and space; however now it is throwing error that MTAR file is not in the path (Error retrieving MTA: Could not find MTA MessageStoreViewer_1.0.0.mtar).
As I mentioned in initial post, I am not sure how to get mtar file. Could you help with that?

Thanks,
Hemant

**Comment by jmailaender** [comment]
Sorry, I missed that part. You can either download the MTAR directly from the [releases page](https://github.com/whint/messagestore-viewer-cf/releases) or build it from the source code as described [here](https://github.com/whint/messagestore-viewer-cf#advanced-options).
